window.$ = window.jQuery = require('jquery')
require('./../../node_modules/pickadate/lib/picker')
require('./../../node_modules/pickadate/lib/picker.date')
require('./../../node_modules/pickadate/lib/picker.time')
require('./../../node_modules/pickadate/lib/translations/fr_FR')
require('bootstrap')
require('./ct-navbar')
window._ = require('lodash')
window.iban = require('./iban')
window.moment = require('moment')
window.moment.locale('fr')
window.validator = require('validator')
window.angular = require('angular')
require('angular-ui-router')
require('angular-ui-bootstrap')
require('angular-sanitize')
require('ngstorage')
require('angular-validator')
require('ngtouch')
require('ng-table')
require('./ng-file-upload-shim')
require('./ng-file-upload')
require('./ng-img-crop')
window.swal = require('./sweetalert.min')